// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQey0els5LHfa9aNo0haKUiqI6o2FSxa4',
    appId: '1:598620011189:web:99eb4e611a3872fea05cfc',
    messagingSenderId: '598620011189',
    projectId: 'expense-tracking-app-ad27a',
    authDomain: 'expense-tracking-app-ad27a.firebaseapp.com',
    databaseURL: 'https://expense-tracking-app-ad27a-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracking-app-ad27a.appspot.com',
    measurementId: 'G-9982WBXH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZQEZuAti46Z6B3OEESmfbvqj0u802js',
    appId: '1:598620011189:android:3cdb9c5a7f59d87ea05cfc',
    messagingSenderId: '598620011189',
    projectId: 'expense-tracking-app-ad27a',
    databaseURL: 'https://expense-tracking-app-ad27a-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracking-app-ad27a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo4oxYu21Jtd8xzs9ckoLq53t7P1lIBp0',
    appId: '1:598620011189:ios:253978b86d7b294ca05cfc',
    messagingSenderId: '598620011189',
    projectId: 'expense-tracking-app-ad27a',
    databaseURL: 'https://expense-tracking-app-ad27a-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracking-app-ad27a.appspot.com',
    iosBundleId: 'com.example.expenseTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo4oxYu21Jtd8xzs9ckoLq53t7P1lIBp0',
    appId: '1:598620011189:ios:253978b86d7b294ca05cfc',
    messagingSenderId: '598620011189',
    projectId: 'expense-tracking-app-ad27a',
    databaseURL: 'https://expense-tracking-app-ad27a-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracking-app-ad27a.appspot.com',
    iosBundleId: 'com.example.expenseTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQey0els5LHfa9aNo0haKUiqI6o2FSxa4',
    appId: '1:598620011189:web:fd79ce52fa86d867a05cfc',
    messagingSenderId: '598620011189',
    projectId: 'expense-tracking-app-ad27a',
    authDomain: 'expense-tracking-app-ad27a.firebaseapp.com',
    databaseURL: 'https://expense-tracking-app-ad27a-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracking-app-ad27a.appspot.com',
    measurementId: 'G-ZRH8MYPCZY',
  );
}
